### ISSUE TITLE
Install location

### ISSUE THREAD

**Issue by shibukawa** [miurahr/omegat-markdown-plugin#13]
README says "~/.omegat/plugin", "C:\Program Files\OmegaT\plugin", but it seems "plugins" (parallel).

And macOS uses ~/Library/Preferences/OmegaT/plugins/ 

http://www.proz.com/forum/omegat_support/222991-installing_okapi_plugins_omegat_macos.html

**Comment by miurahr** [comment]
Thanks for reporting typo... I'll fix it soon.
